"use strict";

define({
  plaqueMessageSmall: {},
  buttonText: {},
  bonusCardTitle: {
    "fontFamily": "hatten",
    "fontSize": 36,
    "dropShadow": true,
    "dropShadowAngle": 0,
    "dropShadowBlur": 5,
    "dropShadowColor": "#fff77e",
    "dropShadowDistance": 0,
    "fill": ["#b7c0ca", "#ffffff", "#94a3b1", "#ccd2d9", "#ffffff"],
    "fillGradientStops": [0.4, 0.5, 0.5, 0.6],
    "fontWeight": "bold",
    "lineJoin": "round",
    "miterLimit": 18,
    "padding": 10,
    "stroke": "#2b0000",
    "strokeThickness": 5
  },
  winningNumbersTitle: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "align": "center",
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    //"fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 26,
    //"lineJoin": "round",
    //"miterLimit": 28,
    //"stroke": "#2d0000",
    //"strokeThickness": 7,
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  winningNumbersTitlePortrait: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "align": "center",
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    //"fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 35,
    //"lineJoin": "round",
    //"miterLimit": 28,
    //"stroke": "#2d0000",
    //"strokeThickness": 7,
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  wheelBonusInfo: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 50,
    "lineJoin": "round",
    "miterLimit": 28,
    "padding": 41,
    //"stroke": "#2d0000",
    //"strokeThickness": 7,
    "align": "center",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  wheelBonusValues: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#5E0000",
    "dropShadowDistance": 0,
    "fill": "#ffffff",
    "fontSize": 60,
    "lineJoin": "round",
    "miterLimit": 28,
    "align": "right",
    "stroke": "#5E0000",
    "strokeThickness": 2,
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  wheelBonusValuesGradient: {
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    //"fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 0,
    "fontSize": 60,
    "lineJoin": "round",
    "miterLimit": 28,
    "align": "right",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  wheelBonusMultiplierValues: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 10,
    "dropShadowColor": "#63180A",
    "dropShadowDistance": 0,
    "fill": ["#ffffff", "#ffeb45", "#faba3b", "#c3963b", "#faba3b", "#ffeb45", "#ffeb45"],
    "fillGradientStops": [0.33, 0.43, 0.47, 0.5, 0.55, 0.7, 0.82],
    "fontSize": 60,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#000000",
    "strokeThickness": 5,
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  defaultPrizeValue: {
    "fill": "#FFFFFF",
    "fontFamily": "Franklin-Gothic-Condensed",
    "dropShadow": true,
    //"dropShadowAngle": 1.7,
    "dropShadowBlur": 2,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1
  },
  prizeValueNoWin: {
    /*
    
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 9,
    "dropShadowColor": "#ffee74",
    "dropShadowDistance": 2,
    "fill": "#603400",
    "fontFamily": "Franklin-Gothic-Condensed",
    "fontSize": 31,
    "lineJoin": "round",
    "miterLimit": 28,
    "padding": 41,
    "stroke": "#ffee74",
    "strokeThickness": 7
    */
    "dropShadow": true,
    "dropShadowBlur": 2,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": "#FFFFFF",
    "fontFamily": "Franklin-Gothic-Condensed",
    //"fontWeight": "normal",
    "align": "center",
    "fontSize": 30,
    "lineJoin": "round",
    "miterLimit": 28,
    "padding": 41
  },
  prizeValueWin: {
    /*
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 4.5,
    "dropShadowColor": "#b32c13",
    "dropShadowDistance": 2,
    "fill": "#ffffff",
    "fontSize": 30,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#2d0000",
    "strokeThickness": 7,
    "fontFamily": "Franklin-Gothic-Condensed"
    */
    "dropShadow": true,
    "dropShadowBlur": 2,
    "dropShadowAngle": 1.7,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": "#FFFFFF",
    "fontFamily": "Franklin-Gothic-Condensed",
    //"fontWeight": "normal",
    "align": "center",
    "fontSize": 30,
    "lineJoin": "round",
    "miterLimit": 28,
    "padding": 41
  },
  prizeValueWinGradient: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 4.5,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 2,
    "fill": ["#ffffff", "#ffeb45", "#faba3b"],
    "fillGradientStops": [0.2, 0.5, 0.8],
    "fontSize": 30,
    "lineJoin": "round",
    "miterLimit": 28,
    //"stroke": "#2d0000",
    //"strokeThickness": 7,
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  prizeValueNoWinMobile: {
    "dropShadow": true,
    "dropShadowBlur": 2,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": "#FFFFFF",
    "fontFamily": "Franklin-Gothic-Condensed",
    //"fontWeight": "normal",
    "align": "center",
    "fontSize": 30,
    "lineJoin": "round",
    "miterLimit": 28,
    "padding": 41
  },
  prizeValueWinMobile: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 4.5,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 2,
    "fill": ["#ffffff", "#ffeb45", "#faba3b"],
    "fillGradientStops": [0.2, 0.5, 0.8],
    "fontSize": 30,
    "lineJoin": "round",
    "miterLimit": 28,
    //"stroke": "#2d0000",
    //"strokeThickness": 7,
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  prizeValueWinGradientMobile: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 4.5,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 2,
    "fill": ["#ffffff", "#ffeb45", "#faba3b"],
    "fillGradientStops": [0.2, 0.5, 0.8],
    "fontSize": 30,
    "lineJoin": "round",
    "miterLimit": 28,
    //"stroke": "#2d0000",
    //"strokeThickness": 7,
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  winUpToText: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": ["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 40,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#2d0000",
    "strokeThickness": 7,
    "align": "center",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  winUpToTextPortrait: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": ["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 40,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#2d0000",
    "strokeThickness": 7,
    "align": "center",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  winUpToValue: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    "fontSize": 50,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#2d0000",
    "strokeThickness": 7,
    "align": "center",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  winUpToValueGradient: {
    "fill": ["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 50,
    "lineJoin": "round",
    "miterLimit": 28,
    "align": "center",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  winUpToValuePortrait: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    "fontSize": 50,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#2d0000",
    "strokeThickness": 7,
    "align": "center",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  winUpToValueGradientPortrait: {
    "fill": ["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 50,
    "lineJoin": "round",
    "miterLimit": 28,
    "align": "center",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  wheelWinUpToLine1Text: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 0,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 70,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#000000",
    "strokeThickness": 2,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  wheelWinUpToLine1TextPortrait: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 0,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 70,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#000000",
    "strokeThickness": 2,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  wheelWinUpToLine2Text: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 0,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 50,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#000000",
    "strokeThickness": 2,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  wheelWinUpToLine2TextPortrait: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 0,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 50,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#000000",
    "strokeThickness": 2,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  wheelBonusTotalWinLabel: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 0,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 42,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#000000",
    "strokeThickness": 2,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  wheelWinMultiplierValue: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#b32c13",
    "dropShadowDistance": 0,
    "fill": ["#ffffff", "#ffeb45", "#faba3b", "#c3963b", "#faba3b", "#ffeb45", "#ffeb45"],
    "fillGradientStops": [0.33, 0.43, 0.47, 0.55, 0.62, 0.7, 0.82],
    "fontSize": 60,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#b32c13",
    "strokeThickness": 1,
    "align": "right",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  wheelWinPrizeValue: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#b32c13",
    "dropShadowDistance": 0,
    "fill": "#ffffff",
    "fontSize": 60,
    "lineJoin": "round",
    "miterLimit": 28,
    "align": "right",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  wheelWinPrizeValueGradient: {
    "fill": ["#ffffff", "#ffeb45", "#faba3b", "#c3963b", "#faba3b", "#ffeb45", "#ffeb45"],
    "fillGradientStops": [0.33, 0.43, 0.47, 0.55, 0.62, 0.7, 0.82],
    "fontSize": 60,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#b32c13",
    "strokeThickness": 1,
    "align": "right",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  ticketSelectCostValue: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#b32c13",
    "dropShadowDistance": 1,
    "fill": "#FFFFED",
    "fontFamily": "oswald",
    "fontSize": 35,
    "fontWeight": "normal",
    "lineJoin": "round",
    "miterLimit": 14
  },
  bonusWin6: {
    fontFamily: 'oswald',
    fontSize: 92,
    fontWeight: 'bold',
    align: 'center',
    fill: 'bonusPayTableWinColour'
  },
  bonusNoWin6: {
    fontFamily: 'oswald',
    fontSize: 92,
    fontWeight: 'bold',
    align: 'center',
    fill: 'bonusPayTableNoWinColour'
  },
  bonusWin5: {
    fontFamily: 'oswald',
    fontSize: 82,
    fontWeight: 'bold',
    align: 'center',
    fill: 'bonusPayTableWinColour'
  },
  bonusNoWin5: {
    fontFamily: 'oswald',
    fontSize: 82,
    fontWeight: 'bold',
    align: 'center',
    fill: 'bonusPayTableNoWinColour'
  },
  bonusWin4: {
    fontFamily: 'oswald',
    fontSize: 72,
    fontWeight: 'bold',
    align: 'center',
    fill: 'bonusPayTableWinColour'
  },
  bonusNoWin4: {
    fontFamily: 'oswald',
    fontSize: 72,
    fontWeight: 'bold',
    align: 'center',
    fill: 'bonusPayTableNoWinColour'
  },
  bonusWin3: {
    fontFamily: 'oswald',
    fontSize: 62,
    fontWeight: 'bold',
    align: 'center',
    fill: 'bonusPayTableWinColour'
  },
  bonusNoWin3: {
    fontFamily: 'oswald',
    fontSize: 62,
    fontWeight: 'bold',
    align: 'center',
    fill: 'bonusPayTableNoWinColour'
  },
  bonusWin: {
    fontFamily: 'oswald',
    fontSize: 62,
    fontWeight: 'bold',
    align: 'center',
    fill: 'bonusPayTableWinColour'
  },
  bonusNoWin: {
    fontFamily: 'oswald',
    fontSize: 62,
    fontWeight: 'bold',
    align: 'center',
    fill: 'bonusPayTableNoWinColour'
  },
  losePlaqueBody: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#b32c13",
    "dropShadowDistance": 1,
    "fill": ["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 65,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#2d0000",
    "strokeThickness": 7,
    "align": "center",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  winPlaqueBody: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#5E0000",
    "dropShadowDistance": 0,
    "fill": ["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 60,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#5E0000",
    "strokeThickness": 2,
    "align": "center",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  bonusLabel: {
    fontFamily: 'oswald',
    fontSize: 32,
    fontWeight: 'bold',
    fill: 'fontColourBonusCover'
  },
  bonusFind3ToEnd: {
    fontFamily: 'oswald',
    fontSize: 30,
    fontWeight: 'bold',
    fill: 'bonusFind3ToEndTextColour'
  },
  bonusFind3ToWin: {
    fontFamily: 'oswald',
    fontSize: 30,
    fontWeight: 'bold',
    fill: 'bonusFind3ToWinTextColour'
  },
  buyButtonEnabled: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#db5a00",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 35,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#db5a00",
    "strokeThickness": 3,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  buyButtonDisabled: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#db5a00",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 35,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#2ddb5a000000",
    "strokeThickness": 3,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  buyButtonOver: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#db5a00",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 35,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#db5a00",
    "strokeThickness": 3,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  buyButtonPressed: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#db5a00",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 35,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#db5a00",
    "strokeThickness": 3,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  footerLabel: {
    padding: 10,
    fontFamily: 'oswald',
    fill: "#ffc43d"
  },
  footerValue: {
    padding: 10,
    fontFamily: 'oswald',
    fill: "#c5c4c2"
  },
  howToPlayTitle: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#b32c13",
    "dropShadowDistance": 1,
    "fill": ["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 46,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#2d0000",
    "strokeThickness": 7,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  howToPlayText: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "black",
    "dropShadowDistance": 2,
    "fontSize": 32,
    "fill": '#dddddd',
    "fontFamily": 'oswald',
    "wordWrap": true,
    "padding": 10
  },
  howToPlayTextCenter: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "black",
    "dropShadowDistance": 2,
    "fontSize": 35,
    "fill": '#dddddd',
    "fontFamily": 'oswald',
    "align": "center",
    "wordWrap": true,
    "padding": 10
  },
  versionText: {
    fontSize: 18,
    fontFamily: 'oswald',
    fill: '#dddddd',
    padding: 10
  },
  totalWinValue: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#b32c13",
    "dropShadowDistance": 0,
    "fill": "#ffffff",
    "fontSize": 120,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#b32c13",
    "strokeThickness": 2,
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  totalWinValueGradient: {
    "fill": ["#ffffff", "#ffeb45", "#faba3b", "#c3963b", "#faba3b", "#ffeb45", "#ffeb45"],
    "fillGradientStops": [0.33, 0.43, 0.47, 0.55, 0.62, 0.7, 0.82],
    "fontSize": 120,
    "lineJoin": "round",
    "miterLimit": 28,
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  errorMessage: {
    fontFamily: 'oswald',
    fontSize: 30,
    align: 'center',
    fill: '#eeeeee',
    padding: 10,
    lineHeight: 40
  },
  mainButtonEnabled: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 35,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#2d0000",
    "strokeThickness": 3,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  mainButtonDisabled: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 35,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#2d0000",
    "strokeThickness": 3,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  mainButtonOver: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 35,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#2d0000",
    "strokeThickness": 3,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  mainButtonPressed: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 35,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#2d0000",
    "strokeThickness": 3,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  tutorialOKButtonEnabled: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#db5a00",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 35,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#db5a00",
    "strokeThickness": 5,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  tutorialOKButtonOver: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#db5a00",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 35,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#db5a00",
    "strokeThickness": 5,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  tutorialOKButtonPressed: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#db5a00",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 35,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#db5a00",
    "strokeThickness": 5,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  collectBonusInfo: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 0,
    "fill": "#ffffff",
    //["#ffffff", "#ffeb45", "#faba3b"],
    //"fillGradientStops": [0.2, 0.5, 0.8],
    "fontSize": 45,
    "lineJoin": "round",
    "miterLimit": 28,
    //"stroke": "#2d0000",
    //"strokeThickness": 2,
    "align": "center",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  collectBonusTotalWin: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 0,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    "fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 42,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#000000",
    "strokeThickness": 2,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  collectBonus: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#421500",
    "dropShadowDistance": 0,
    "fill": ["#ffffff", "#ffeb45", "#faba3b", "#c3963b", "#faba3b", "#ffeb45", "#ffeb45"],
    "fillGradientStops": [0.33, 0.43, 0.47, 0.55, 0.62, 0.7, 0.82],
    "fontSize": 50,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#421500",
    "strokeThickness": 2,
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  collectBonusValuePicker: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 5,
    "dropShadowColor": "#421500",
    "dropShadowDistance": 0,
    "fill": "#ffffff",
    "fontSize": 60,
    "lineJoin": "round",
    "miterLimit": 28,
    "stroke": "#421500",
    "strokeThickness": 2,
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  collectBonusValuePickerGradient: {
    "fill": ["#ffffff", "#ffeb45", "#faba3b", "#c3963b", "#faba3b", "#ffeb45", "#ffeb45"],
    "fillGradientStops": [0.33, 0.43, 0.47, 0.55, 0.62, 0.7, 0.82],
    "fontSize": 60,
    "lineJoin": "round",
    "miterLimit": 28,
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  errorButtonEnabled: {
    fontFamily: 'oswald',
    fontSize: 38,
    fill: '#ffffff',
    padding: 10
  },
  errorButtonOver: {
    fontFamily: 'oswald',
    fontSize: 38,
    fill: '#ffffff',
    padding: 10
  },
  errorButtonPressed: {
    fontFamily: 'oswald',
    fontSize: 41,
    fill: '#ffffff',
    padding: 10
  },
  bonusCards: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    //"fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 40,
    //"lineJoin": "round",
    "miterLimit": 18,
    "padding": 10,
    //"lineHeight": 30,
    //"stroke": "#2d0000",
    //"strokeThickness": 7,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  },
  bonusCardsPortrait: {
    "dropShadow": true,
    "dropShadowAngle": 1.7,
    "dropShadowBlur": 1,
    "dropShadowColor": "#000000",
    "dropShadowDistance": 1,
    "fill": "#ffffff",
    //["#ffffff", "#ffffd1", "#fff9c1", "#d3b57b"],
    //"fillGradientStops": [0.4, 0.4, 0.5, 0.7],
    "fontSize": 35,
    //"lineJoin": "round",
    "miterLimit": 18,
    "padding": 10,
    //"miterLimit": 28,
    //"lineHeight": 30,
    //"stroke": "#2d0000",
    //"strokeThickness": 7,
    "align": "left",
    "fontFamily": "Franklin-Gothic-Condensed"
  }
});